In [ ]:
import sys
sys.path.insert(0, "./../") 

from common.datasets_util import get_sent_for_pos, get_info
from common.sanskrit_texts import Datasources
from common.vocab_util import build_vocabulary, pos_corpus_to_tensor,build_akshara_vocabulary
from common.conllu_util import get_files_conllu, read_conllu_file

In [20]:
#_TEXTS_DIR = os.environ.get("SANSKRIT_TEXTS_DIR")
_TEXTS_DIR = '../../../sanskrit_texts'

In [ ]:
texts = [Datasources.MAHABHARATA, Datasources.RAMAYANA, Datasources.AMARAKOSHA, Datasources.HITOPADESHA]

files = [file for text in texts for file in get_files_conllu(f"{_TEXTS_DIR}/{text}/")]

df, sentences, all_tokens = read_conllu_file(files)

sent_count = len(sentences)

sentences_splited = [' '.join([s['form'] for s in sent if str(s['id']).isdigit()]) for sent in sentences]

all_tokens_clean = [(token['form'], token['upos'], token['feats']) for token in all_tokens if str(token['id']).isdigit()]

df_clean = df[df['upos'] != '_']
df_clean = df_clean.reset_index()

df_clean['sent'] = get_sent_for_pos(df_clean, sent_count)

df_clean['pos'] = df_clean.apply(lambda row: get_info(row).rstrip(), axis=1)

In [74]:
df_clean['pos'] = df_clean.apply(lambda row: get_info(row).rstrip(), axis=1)
vc = df_clean['pos'].value_counts()
ones = vc[vc == 1]
len(ones)

83

In [48]:
ones

pos
VERB Acc Fem Dual Gdv           1
ADJ Nom Dual                    1
VERB Opt Sing 3 Pres Pass       1
VERB Loc Neut Sing Past Part    1
VERB Past Jus 3 Dual            1
                               ..
VERB Ind Dual 3 Pres            1
ADJ Dat Neut Plur               1
VERB Loc Masc Plur Fut Part     1
VERB Ind Plur 2 Fut             1
VERB Loc Masc Dual Fut Part     1
Name: count, Length: 83, dtype: int64

In [49]:
df_clean[df_clean['pos'] == 'VERB Voc Neut Plur Pres Part']

,index,id,form,lemma,upos,xpos,feats,head,deprel,deps,misc,sent,pos
1104847,1300506,2,arhanti,arh,VERB,None,"{'Case': 'Voc', 'Gender': 'Neut', 'Number': 'P...",NaN,_,None,"{'LemmaId': '156118', 'OccId': '751830', 'Unsa...",162029,VERB Voc Neut Plur Pres Part

In [50]:
df_clean[df_clean['form'] == 'arhanti']

,index,id,form,lemma,upos,xpos,feats,head,deprel,deps,misc,sent,pos
84060,99030,9,arhanti,arh,VERB,None,"{'Tense': 'Pres', 'Mood': 'Ind', 'Person': '3'...",NaN,_,None,"{'LemmaId': '156118', 'OccId': '3886920', 'Uns...",12349,VERB Pres Ind 3 Plur
84079,99053,8,arhanti,arh,VERB,None,"{'Tense': 'Pres', 'Mood': 'Ind', 'Person': '3'...",NaN,_,None,"{'LemmaId': '156118', 'OccId': '3886939', 'Uns...",12351,VERB Pres Ind 3 Plur
84092,99069,7,arhanti,arh,VERB,None,"{'Tense': 'Pres', 'Mood': 'Ind', 'Person': '3'...",NaN,_,None,"{'LemmaId': '156118', 'OccId': '3886952', 'Uns...",12353,VERB Pres Ind 3 Plur
84107,99088,7,arhanti,arh,VERB,None,"{'Tense': 'Pres', 'Mood': 'Ind', 'Person': '3'...",NaN,_,None,"{'LemmaId': '156118', 'OccId': '3886967', 'Uns...",12355,VERB Pres Ind 3 Plur
84121,99105,7,arhanti,arh,VERB,None,"{'Tense': 'Pres', 'Mood': 'Ind', 'Person': '3'...",NaN,_,None,"{'LemmaId': '156118', 'OccId': '3886981', 'Uns...",12357,VERB Pres Ind 3 Plur
84168,99163,8,arhanti,arh,VERB,None,"{'Tense': 'Pres', 'Mood': 'Ind', 'Person': '3'...",NaN,_,None,"{'LemmaId': '156118', 'OccId': '3887027', 'Uns...",12363,VERB Pres Ind 3 Plur
84184,99183,7,arhanti,arh,VERB,None,"{'Tense': 'Pres', 'Mood': 'Ind', 'Person': '3'...",NaN,_,None,"{'LemmaId': '156118', 'OccId': '3887035', 'Uns...",12365,VERB Pres Ind 3 Plur
84201,99204,7,arhanti,arh,VERB,None,"{'Tense': 'Pres', 'Mood': 'Ind', 'Person': '3'...",NaN,_,None,"{'LemmaId': '156118', 'OccId': '3887052', 'Uns...",12367,VERB Pres Ind 3 Plur
84216,99224,7,arhanti,arh,VERB,None,"{'Tense': 'Pres', 'Mood': 'Ind', 'Person': '3'...",NaN,_,None,"{'LemmaId': '156118', 'OccId': '3887067', 'Uns...",12369,VERB Pres Ind 3 Plur
149987,176887,6,arhanti,arh,VERB,None,"{'Tense': 'Pres', 'Mood': 'Ind', 'Person': '3'...",NaN,_,None,"{'LemmaId': '156118', 'OccId': '2408726', 'Uns...",22036,VERB Pres Ind 3 Plur
150010,176917,3,arhanti,arh,VERB,None,"{'Tense': 'Pres', 'Mood': 'Ind', 'Person': '3'...",NaN,_,None,"{'LemmaId': '156118', 'OccId': '2408749', 'Uns...",22040,VERB Pres Ind 3 Plur
266769,314215,2,arhanti,arh,VERB,None,"{'Tense': 'Pres', 'Mood': 'Ind', 'Person': '3'...",NaN,_,None,"{'LemmaId': '156118', 'OccId': '969806', 'Unsa...",39138,VERB Pres Ind 3 Plur
304129,358250,5,arhanti,arh,VERB,None,"{'Tense': 'Pres', 'Mood': 'Ind', 'Person': '3'...",NaN,_,None,"{'LemmaId': '156118', 'OccId': '3548918', 'Uns...",44715,VERB Pres Ind 3 Plur
313395,369100,5,arhanti,arh,VERB,None,"{'Tense': 'Pres', 'Mood': 'Ind', 'Person': '3'...",NaN,_,None,"{'LemmaId': '156118', 'OccId': '2644549', 'Uns...",46040,VERB Pres Ind 3 Plur
397475,467932,7,arhanti,arh,VERB,None,"{'Tense': 'Pres', 'Mood': 'Ind', 'Person': '3'...",NaN,_,None,"{'LemmaId': '156118', 'OccId': '3942292', 'Uns...",58387,VERB Pres Ind 3 Plur
409112,481563,4,arhanti,arh,VERB,None,"{'Tense': 'Pres', 'Mood': 'Ind', 'Person': '3'...",NaN,_,None,"{'LemmaId': '156118', 'OccId': '3437504', 'Uns...",60075,VERB Pres Ind 3 Plur
571671,673064,3,arhanti,arh,VERB,None,"{'Tense': 'Pres', 'Mood': 'Ind', 'Person': '3'...",NaN,_,None,"{'LemmaId': '156118', 'OccId': '3075487', 'Uns...",83789,VERB Pres Ind 3 Plur
590067,694620,4,arhanti,arh,VERB,None,"{'Tense': 'Pres', 'Mood': 'Ind', 'Person': '3'...",NaN,_,None,"{'LemmaId': '156118', 'OccId': '3898049', 'Uns...",86510,VERB Pres Ind 3 Plur
643040,756899,6,arhanti,arh,VERB,None,"{'Tense': 'Pres', 'Mood': 'Ind', 'Person': '3'...",NaN,_,None,"{'LemmaId': '156118', 'OccId': '3127922', 'Uns...",94230,VERB Pres Ind 3 Plur
646698,761249,7,arhanti,arh,VERB,None,"{'Tense': 'Pres', 'Mood': 'Ind', 'Person': '3'...",NaN,_,None,"{'LemmaId': '156118', 'OccId': '2641906', 'Uns...",94778,VERB Pres Ind 3 Plur
648724,763634,6,arhanti,arh,VERB,None,"{'Tense': 'Pres', 'Mood': 'Ind', 'Person': '3'...",NaN,_,None,"{'LemmaId': '156118', 'OccId': '3436974', 'Uns...",95086,VERB Pres Ind 3 Plur
704950,829633,1,arhanti,arh,VERB,None,"{'Tense': 'Pres', 'Mood': 'Ind', 'Person': '3'...",NaN,_,None,"{'LemmaId': '156118', 'OccId': '3108279', 'Uns...",103328,VERB Pres Ind 3 Plur
788240,927972,3,arhanti,arh,VERB,None,"{'Tense': 'Pres', 'Mood': 'Ind', 'Person': '3'...",NaN,_,None,"{'LemmaId': '156118', 'OccId': '3973477', 'Uns...",115548,VERB Pres Ind 3 Plur
815343,959735,3,arhanti,arh,VERB,None,"{'Tense': 'Pres', 'Mood': 'Ind', 'Person': '3'...",NaN,_,None,"{'LemmaId': '156118', 'OccId': '3899025', 'Uns...",119621,VERB Pres Ind 3 Plur
823887,969774,7,arhanti,arh,VERB,None,"{'Tense': 'Pres', 'Mood': 'Ind', 'Person': '3'...",NaN,_,None,"{'LemmaId': '156118', 'OccId': '3760568', 'Uns...",120853,VERB Pres Ind 3 Plur
829980,977001,6,arhanti,arh,VERB,None,"{'Tense': 'Pres', 'Mood': 'Ind', 'Person': '3'...",NaN,_,None,"{'LemmaId': '156118', 'OccId': '1040019', 'Uns...",121760,VERB Pres Ind 3 Plur
853147,1004330,8,arhanti,arh,VERB,None,"{'Tense': 'Pres', 'Mood': 'Ind', 'Person': '3'...",NaN,_,None,"{'LemmaId': '156118', 'OccId': '3962685', 'Uns...",125069,VERB Pres Ind 3 Plur
856182,1007974,6,arhanti,arh,VERB,None,"{'Tense': 'Pres', 'Mood': 'Ind', 'Person': '3'...",NaN,_,None,"{'LemmaId': '156118', 'OccId': '3894637', 'Uns...",125502,VERB Pres Ind 3 Plur
865795,1019468,3,arhanti,arh,VERB,None,"{'Tense': 'Pres', 'Mood': 'Ind', 'Person': '3'...",NaN,_,None,"{'LemmaId': '156118', 'OccId': '2434829', 'Uns...",126893,VERB Pres Ind 3 Plur
874224,1029359,7,arhanti,arh,VERB,None,"{'Tense': 'Pres', 'Mood': 'Ind', 'Person': '3'...",NaN,_,None,"{'LemmaId': '156118', 'OccId': '851991', 'Unsa...",128102,VERB Pres Ind 3 Plur
882454,1039031,10,arhanti,arh,VERB,None,"{'Tense': 'Pres', 'Mood': 'Ind', 'Person': '3'...",NaN,_,None,"{'LemmaId': '156118', 'OccId': '3953661', 'Uns...",129240,VERB Pres Ind 3 Plur
914077,1076246,2,arhanti,arh,VERB,None,"{'Tense': 'Pres', 'Mood': 'Ind', 'Person': '3'...",NaN,_,None,"{'LemmaId': '156118', 'OccId': '3505683', 'Uns...",133982,VERB Pres Ind 3 Plur
933271,1098698,3,arhanti,arh,VERB,None,"{'Tense': 'Pres', 'Mood': 'Ind', 'Person': '3'...",NaN,_,None,"{'LemmaId': '156118', 'OccId': '2646432', 'Uns...",136834,VERB Pres Ind 3 Plur
994256,1170639,6,arhanti,arh,VERB,None,"{'Tense': 'Pres', 'Mood': 'Ind', 'Person': '3'...",NaN,_,None,"{'LemmaId': '156118', 'OccId': '1122528', 'Uns...",145766,VERB Pres Ind 3 Plur
1104847,1300506,2,arhanti,arh,VERB,None,"{'Case': 'Voc', 'Gender': 'Neut', 'Number': 'P...",NaN,_,None,"{'LemmaId': '156118', 'OccId': '751830', 'Unsa...",162029,VERB Voc Neut Plur Pres Part
1245653,1465489,6,arhanti,arh,VERB,None,"{'Tense': 'Pres', 'Mood': 'Ind', 'Person': '3'...",NaN,_,None,"{'LemmaId': '156118', 'OccId': '414435', 'Unsa...",182641,VERB Pres Ind 3 Plur

In [51]:
df_clean['pos'].value_counts()

pos
NOUN Cpd                       118065
NOUN Nom Masc Sing              95404
PART                            94972
ADV                             94761
CONJ                            63301
                                ...
VERB Ind Dual 3 Pres                1
ADJ Dat Neut Plur                   1
VERB Loc Masc Plur Fut Part         1
VERB Ind Plur 2 Fut                 1
VERB Loc Masc Dual Fut Part         1
Name: count, Length: 733, dtype: int64

In [53]:
df_clean_ones = df_clean[df_clean['pos'].isin(ones.index)]
df_clean_ones

,index,id,form,lemma,upos,xpos,feats,head,deprel,deps,misc,sent,pos
2202,2578,26,karavāṇi,kṛ,VERB,None,"{'Mood': 'Imp', 'Number': 'Sing', 'Person': '1...",24.0,ccomp,None,"{'LemmaId': '156168', 'OccId': '1261968', 'Uns...",313,VERB Imp Sing 1 Pres
2336,2713,33,yuktāni,yuj,VERB,None,"{'Case': 'Nom', 'Gender': 'Neut', 'Number': 'P...",31.0,conj,None,"{'LemmaId': '157298', 'OccId': '1262093', 'Uns...",323,VERB Nom Neut Plur Past Part
2447,2826,4,anukuryuḥ,anukṛ,VERB,None,"{'Mood': 'Opt', 'Number': 'Plur', 'Person': '3...",16.0,acl:rel,None,"{'LemmaId': '157687', 'OccId': '1262198', 'Uns...",340,VERB Opt Plur 3 Pres
6250,7289,6,bhaviṣyatī,bhū,VERB,None,"{'Case': 'Acc', 'Gender': 'Neut', 'Number': 'D...",NaN,_,None,"{'LemmaId': '157250', 'OccId': '2599505', 'Uns...",909,VERB Acc Neut Dual Fut Part
24489,28924,6,tasthivasām,sthā,VERB,None,"{'Case': 'Gen', 'Gender': 'Neut', 'Number': 'P...",NaN,_,None,"{'LemmaId': '157340', 'OccId': '3400925', 'Uns...",3602,VERB Gen Neut Plur Past Part
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1329411,1563698,7,_,dūṣaka,ADJ,None,"{'Case': 'Nom', 'Number': 'Dual'}",NaN,_,None,"{'LemmaId': '86082', 'OccId': '444054', 'Unsan...",194848,ADJ Nom Dual
1338499,1574367,4,bhārye,bhṛ,VERB,None,"{'Case': 'Acc', 'Gender': 'Fem', 'Number': 'Du...",NaN,_,None,"{'LemmaId': '157419', 'OccId': '1830245', 'Uns...",196173,VERB Acc Fem Dual Gdv
1380570,1623739,1,vidheyānāṃ,vidhā,VERB,None,"{'Case': 'Gen', 'Gender': 'Fem', 'Number': 'Pl...",NaN,_,None,"{'LemmaId': '163351', 'OccId': '1739910', 'Uns...",202298,VERB Gen Fem Plur Gdv
1394144,1639672,6,abhibhāṣitam,abhibhāṣ,VERB,None,"{'Case': 'Voc', 'Gender': 'Neut', 'Number': 'S...",NaN,_,None,"{'LemmaId': '158871', 'OccId': '1308299', 'Uns...",204223,VERB Voc Neut Sing Part
1415527,1664882,5,vakṣyamāṇayoḥ,vac,VERB,None,"{'Case': 'Loc', 'Gender': 'Masc', 'Number': 'D...",NaN,_,None,"{'LemmaId': '157264', 'OccId': '4226829', 'Uns...",207460,VERB Loc Masc Dual Fut Part

In [60]:
df_clean_ones['id'] = range(1, len(df_clean_ones) + 1)
df_clean_ones

/var/folders/k5/kncgbhf91wx7y2rd9hqw9yqm0000gq/T/ipykernel_52511/1755257542.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean_ones['id'] = range(1, len(df_clean_ones) + 1)

,index,id,form,lemma,upos,xpos,feats,head,deprel,deps,misc,sent,pos
2202,2578,1,karavāṇi,kṛ,VERB,None,"{'Mood': 'Imp', 'Number': 'Sing', 'Person': '1...",24.0,ccomp,None,"{'LemmaId': '156168', 'OccId': '1261968', 'Uns...",211494,VERB Imp Sing 1 Pres
2336,2713,2,yuktāni,yuj,VERB,None,"{'Case': 'Nom', 'Gender': 'Neut', 'Number': 'P...",31.0,conj,None,"{'LemmaId': '157298', 'OccId': '1262093', 'Uns...",211494,VERB Nom Neut Plur Past Part
2447,2826,3,anukuryuḥ,anukṛ,VERB,None,"{'Mood': 'Opt', 'Number': 'Plur', 'Person': '3...",16.0,acl:rel,None,"{'LemmaId': '157687', 'OccId': '1262198', 'Uns...",211494,VERB Opt Plur 3 Pres
6250,7289,4,bhaviṣyatī,bhū,VERB,None,"{'Case': 'Acc', 'Gender': 'Neut', 'Number': 'D...",NaN,_,None,"{'LemmaId': '157250', 'OccId': '2599505', 'Uns...",211494,VERB Acc Neut Dual Fut Part
24489,28924,5,tasthivasām,sthā,VERB,None,"{'Case': 'Gen', 'Gender': 'Neut', 'Number': 'P...",NaN,_,None,"{'LemmaId': '157340', 'OccId': '3400925', 'Uns...",211494,VERB Gen Neut Plur Past Part
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1329411,1563698,79,_,dūṣaka,ADJ,None,"{'Case': 'Nom', 'Number': 'Dual'}",NaN,_,None,"{'LemmaId': '86082', 'OccId': '444054', 'Unsan...",211494,ADJ Nom Dual
1338499,1574367,80,bhārye,bhṛ,VERB,None,"{'Case': 'Acc', 'Gender': 'Fem', 'Number': 'Du...",NaN,_,None,"{'LemmaId': '157419', 'OccId': '1830245', 'Uns...",211494,VERB Acc Fem Dual Gdv
1380570,1623739,81,vidheyānāṃ,vidhā,VERB,None,"{'Case': 'Gen', 'Gender': 'Fem', 'Number': 'Pl...",NaN,_,None,"{'LemmaId': '163351', 'OccId': '1739910', 'Uns...",211494,VERB Gen Fem Plur Gdv
1394144,1639672,82,abhibhāṣitam,abhibhāṣ,VERB,None,"{'Case': 'Voc', 'Gender': 'Neut', 'Number': 'S...",NaN,_,None,"{'LemmaId': '158871', 'OccId': '1308299', 'Uns...",211494,VERB Voc Neut Sing Part
1415527,1664882,83,vakṣyamāṇayoḥ,vac,VERB,None,"{'Case': 'Loc', 'Gender': 'Masc', 'Number': 'D...",NaN,_,None,"{'LemmaId': '157264', 'OccId': '4226829', 'Uns...",211494,VERB Loc Masc Dual Fut Part

In [58]:
import pandas as pd

df_clean_ones['sent'] = sent_count + 1

df_clean_with_ones = pd.concat([df_clean, df_clean_ones], ignore_index=True)
df_clean_with_ones

/var/folders/k5/kncgbhf91wx7y2rd9hqw9yqm0000gq/T/ipykernel_52511/1310684056.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean_ones['sent'] = sent_count + 1

,index,id,form,lemma,upos,xpos,feats,head,deprel,deps,misc,sent,pos
0,0,1,vaiśaṃpāyana,vaiśampāyana,NOUN,None,"{'Case': 'Nom', 'Gender': 'Masc', 'Number': 'S...",NaN,_,None,"{'LemmaId': '118517', 'OccId': '1115569', 'Uns...",0,NOUN Nom Masc Sing
1,1,2,uvāca,vac,VERB,None,"{'Tense': 'Past', 'Mood': 'Ind', 'Person': '3'...",NaN,_,None,"{'LemmaId': '157264', 'OccId': '1115570', 'Uns...",0,VERB Past Ind 3 Sing
2,2,1,tatra,tatra,ADV,None,None,NaN,_,None,"{'LemmaId': '95978', 'OccId': '1115571', 'Unsa...",1,ADV
3,3,2,teṣu,tad,PRON,None,"{'Case': 'Loc', 'Gender': 'Masc', 'Number': 'P...",NaN,_,None,"{'LemmaId': '37875', 'OccId': '1115572', 'Unsa...",1,PRON Loc Masc Plur
4,4,3,śayāneṣu,śī,VERB,None,"{'Case': 'Loc', 'Gender': 'Masc', 'Number': 'P...",NaN,_,None,"{'LemmaId': '157336', 'OccId': '1115573', 'Uns...",1,VERB Loc Masc Plur Pres Part
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1444567,1563698,7,_,dūṣaka,ADJ,None,"{'Case': 'Nom', 'Number': 'Dual'}",NaN,_,None,"{'LemmaId': '86082', 'OccId': '444054', 'Unsan...",211494,ADJ Nom Dual
1444568,1574367,4,bhārye,bhṛ,VERB,None,"{'Case': 'Acc', 'Gender': 'Fem', 'Number': 'Du...",NaN,_,None,"{'LemmaId': '157419', 'OccId': '1830245', 'Uns...",211494,VERB Acc Fem Dual Gdv
1444569,1623739,1,vidheyānāṃ,vidhā,VERB,None,"{'Case': 'Gen', 'Gender': 'Fem', 'Number': 'Pl...",NaN,_,None,"{'LemmaId': '163351', 'OccId': '1739910', 'Uns...",211494,VERB Gen Fem Plur Gdv
1444570,1639672,6,abhibhāṣitam,abhibhāṣ,VERB,None,"{'Case': 'Voc', 'Gender': 'Neut', 'Number': 'S...",NaN,_,None,"{'LemmaId': '158871', 'OccId': '1308299', 'Uns...",211494,VERB Voc Neut Sing Part
1444571,1664882,5,vakṣyamāṇayoḥ,vac,VERB,None,"{'Case': 'Loc', 'Gender': 'Masc', 'Number': 'D...",NaN,_,None,"{'LemmaId': '157264', 'OccId': '4226829', 'Uns...",211494,VERB Loc Masc Dual Fut Part

In [57]:
df_clean_with_ones.reset_index()

,level_0,index,id,form,lemma,upos,xpos,feats,head,deprel,deps,misc,sent,pos
0,0,0,1,vaiśaṃpāyana,vaiśampāyana,NOUN,None,"{'Case': 'Nom', 'Gender': 'Masc', 'Number': 'S...",NaN,_,None,"{'LemmaId': '118517', 'OccId': '1115569', 'Uns...",0,NOUN Nom Masc Sing
1,1,1,2,uvāca,vac,VERB,None,"{'Tense': 'Past', 'Mood': 'Ind', 'Person': '3'...",NaN,_,None,"{'LemmaId': '157264', 'OccId': '1115570', 'Uns...",0,VERB Past Ind 3 Sing
2,2,2,1,tatra,tatra,ADV,None,None,NaN,_,None,"{'LemmaId': '95978', 'OccId': '1115571', 'Unsa...",1,ADV
3,3,3,2,teṣu,tad,PRON,None,"{'Case': 'Loc', 'Gender': 'Masc', 'Number': 'P...",NaN,_,None,"{'LemmaId': '37875', 'OccId': '1115572', 'Unsa...",1,PRON Loc Masc Plur
4,4,4,3,śayāneṣu,śī,VERB,None,"{'Case': 'Loc', 'Gender': 'Masc', 'Number': 'P...",NaN,_,None,"{'LemmaId': '157336', 'OccId': '1115573', 'Uns...",1,VERB Loc Masc Plur Pres Part
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1444567,1329411,1563698,7,_,dūṣaka,ADJ,None,"{'Case': 'Nom', 'Number': 'Dual'}",NaN,_,None,"{'LemmaId': '86082', 'OccId': '444054', 'Unsan...",211494,ADJ Nom Dual
1444568,1338499,1574367,4,bhārye,bhṛ,VERB,None,"{'Case': 'Acc', 'Gender': 'Fem', 'Number': 'Du...",NaN,_,None,"{'LemmaId': '157419', 'OccId': '1830245', 'Uns...",211494,VERB Acc Fem Dual Gdv
1444569,1380570,1623739,1,vidheyānāṃ,vidhā,VERB,None,"{'Case': 'Gen', 'Gender': 'Fem', 'Number': 'Pl...",NaN,_,None,"{'LemmaId': '163351', 'OccId': '1739910', 'Uns...",211494,VERB Gen Fem Plur Gdv
1444570,1394144,1639672,6,abhibhāṣitam,abhibhāṣ,VERB,None,"{'Case': 'Voc', 'Gender': 'Neut', 'Number': 'S...",NaN,_,None,"{'LemmaId': '158871', 'OccId': '1308299', 'Uns...",211494,VERB Voc Neut Sing Part
1444571,1415527,1664882,5,vakṣyamāṇayoḥ,vac,VERB,None,"{'Case': 'Loc', 'Gender': 'Masc', 'Number': 'D...",NaN,_,None,"{'LemmaId': '157264', 'OccId': '4226829', 'Uns...",211494,VERB Loc Masc Dual Fut Part

In [ ]:
df_clean_with_ones['pos'] = df_clean_with_ones.apply(lambda row: get_info(row).rstrip(), axis=1)
vc = df_clean_with_ones['pos'].value_counts()
ones = vc[vc == 1]
len(ones)

0

In [82]:
df_clean['pos'] = df_clean.apply(lambda row: get_info(row).rstrip(), axis=1)
vc = df_clean['pos'].value_counts()
ones = vc[vc == 1]
len(ones)

83

In [ ]:
df_clean_ones = df_clean[df_clean['pos'].isin(ones.index)]
df_clean_ones

,index,id,form,lemma,upos,xpos,feats,head,deprel,deps,misc,sent,pos
2202,2578,26,karavāṇi,kṛ,VERB,None,"{'Mood': 'Imp', 'Number': 'Sing', 'Person': '1...",24.0,ccomp,None,"{'LemmaId': '156168', 'OccId': '1261968', 'Uns...",313,VERB Imp Sing 1 Pres
2336,2713,33,yuktāni,yuj,VERB,None,"{'Case': 'Nom', 'Gender': 'Neut', 'Number': 'P...",31.0,conj,None,"{'LemmaId': '157298', 'OccId': '1262093', 'Uns...",323,VERB Nom Neut Plur Past Part
2447,2826,4,anukuryuḥ,anukṛ,VERB,None,"{'Mood': 'Opt', 'Number': 'Plur', 'Person': '3...",16.0,acl:rel,None,"{'LemmaId': '157687', 'OccId': '1262198', 'Uns...",340,VERB Opt Plur 3 Pres
6250,7289,6,bhaviṣyatī,bhū,VERB,None,"{'Case': 'Acc', 'Gender': 'Neut', 'Number': 'D...",NaN,_,None,"{'LemmaId': '157250', 'OccId': '2599505', 'Uns...",909,VERB Acc Neut Dual Fut Part
24489,28924,6,tasthivasām,sthā,VERB,None,"{'Case': 'Gen', 'Gender': 'Neut', 'Number': 'P...",NaN,_,None,"{'LemmaId': '157340', 'OccId': '3400925', 'Uns...",3602,VERB Gen Neut Plur Past Part
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1329411,1563698,7,_,dūṣaka,ADJ,None,"{'Case': 'Nom', 'Number': 'Dual'}",NaN,_,None,"{'LemmaId': '86082', 'OccId': '444054', 'Unsan...",194848,ADJ Nom Dual
1338499,1574367,4,bhārye,bhṛ,VERB,None,"{'Case': 'Acc', 'Gender': 'Fem', 'Number': 'Du...",NaN,_,None,"{'LemmaId': '157419', 'OccId': '1830245', 'Uns...",196173,VERB Acc Fem Dual Gdv
1380570,1623739,1,vidheyānāṃ,vidhā,VERB,None,"{'Case': 'Gen', 'Gender': 'Fem', 'Number': 'Pl...",NaN,_,None,"{'LemmaId': '163351', 'OccId': '1739910', 'Uns...",202298,VERB Gen Fem Plur Gdv
1394144,1639672,6,abhibhāṣitam,abhibhāṣ,VERB,None,"{'Case': 'Voc', 'Gender': 'Neut', 'Number': 'S...",NaN,_,None,"{'LemmaId': '158871', 'OccId': '1308299', 'Uns...",204223,VERB Voc Neut Sing Part
1415527,1664882,5,vakṣyamāṇayoḥ,vac,VERB,None,"{'Case': 'Loc', 'Gender': 'Masc', 'Number': 'D...",NaN,_,None,"{'LemmaId': '157264', 'OccId': '4226829', 'Uns...",207460,VERB Loc Masc Dual Fut Part

In [87]:
new_sents = df_clean_ones['sent'].value_counts()
new_sents
new_df_sents = []
for i_sent in new_sents.index:
    new_df_sent = df_clean[df_clean['sent'] == i_sent]
    new_df_sent['sent'] = sent_count
    sent_count += 1
    new_df_sents.append(new_df_sent)

df_clean = pd.concat([df_clean] + new_df_sents, ignore_index=True)
df_clean

/var/folders/k5/kncgbhf91wx7y2rd9hqw9yqm0000gq/T/ipykernel_52511/1345332766.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df_sent['sent'] = sent_count

,index,id,form,lemma,upos,xpos,feats,head,deprel,deps,misc,sent,pos
0,0,1,vaiśaṃpāyana,vaiśampāyana,NOUN,None,"{'Case': 'Nom', 'Gender': 'Masc', 'Number': 'S...",NaN,_,None,"{'LemmaId': '118517', 'OccId': '1115569', 'Uns...",0,NOUN Nom Masc Sing
1,1,2,uvāca,vac,VERB,None,"{'Tense': 'Past', 'Mood': 'Ind', 'Person': '3'...",NaN,_,None,"{'LemmaId': '157264', 'OccId': '1115570', 'Uns...",0,VERB Past Ind 3 Sing
2,2,1,tatra,tatra,ADV,None,None,NaN,_,None,"{'LemmaId': '95978', 'OccId': '1115571', 'Unsa...",1,ADV
3,3,2,teṣu,tad,PRON,None,"{'Case': 'Loc', 'Gender': 'Masc', 'Number': 'P...",NaN,_,None,"{'LemmaId': '37875', 'OccId': '1115572', 'Unsa...",1,PRON Loc Masc Plur
4,4,3,śayāneṣu,śī,VERB,None,"{'Case': 'Loc', 'Gender': 'Masc', 'Number': 'P...",NaN,_,None,"{'LemmaId': '157336', 'OccId': '1115573', 'Uns...",1,VERB Loc Masc Plur Pres Part
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1445171,1664877,1,striyām,strī,NOUN,None,"{'Case': 'Loc', 'Gender': 'Fem', 'Number': 'Si...",NaN,_,None,"{'LemmaId': '102548', 'OccId': '4226825', 'Uns...",211575,NOUN Loc Fem Sing
1445172,1664878,2,sphicau,sphic,NOUN,None,"{'Case': 'Nom', 'Gender': 'Fem', 'Number': 'Du...",NaN,_,None,"{'LemmaId': '113796', 'OccId': '4226826', 'Uns...",211575,NOUN Nom Fem Dual
1445173,1664880,3,kaṭiprothau,kaṭiprotha,NOUN,None,"{'Case': 'Nom', 'Gender': 'Masc', 'Number': 'D...",NaN,_,None,"{'LemmaId': '780', 'OccId': '4226827', 'Unsand...",211575,NOUN Nom Masc Dual
1445174,1664881,4,upasthaḥ,upastha,NOUN,None,"{'Case': 'Nom', 'Gender': 'Masc', 'Number': 'S...",NaN,_,None,"{'LemmaId': '45827', 'OccId': '4226828', 'Unsa...",211575,NOUN Nom Masc Sing
1445175,1664882,5,vakṣyamāṇayoḥ,vac,VERB,None,"{'Case': 'Loc', 'Gender': 'Masc', 'Number': 'D...",NaN,_,None,"{'LemmaId': '157264', 'OccId': '4226829', 'Uns...",211575,VERB Loc Masc Dual Fut Part

In [ ]:

df_clean_ones['sent'] = range(sent_count, sent_count + len(ones))
sent_count += len(ones)
df_clean_ones['id'] = 1
df_clean = pd.concat([df_clean, df_clean_ones], ignore_index=True)

/var/folders/k5/kncgbhf91wx7y2rd9hqw9yqm0000gq/T/ipykernel_52511/3694036785.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean_ones['sent'] = range(sent_count, sent_count + len(ones))
/var/folders/k5/kncgbhf91wx7y2rd9hqw9yqm0000gq/T/ipykernel_52511/3694036785.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean_ones['id'] = 1

In [94]:
df_clean = pd.concat([df_clean, df_clean], ignore_index=True)

In [95]:
max_sent_len = max(len(sent) for sent in sentences_splited)
max_origin_token_len = max(len(token[0]) for token in all_tokens_clean)

char_tokenized = [list(sent) for sent in sentences_splited]

char2id, _ = build_vocabulary(char_tokenized, max_doc_freq=1.0, min_count=5, pad_word='<PAD>')

unique_tags = ['<NOTAG>'] + sorted(df_clean['pos'].value_counts().index)
label2id = {label: i for i, label in enumerate(unique_tags)}

inputs, labels = pos_corpus_to_tensor(df_clean[['sent', 'id', 'form', 'pos']], char2id, label2id, sent_count, max_sent_len, max_origin_token_len)

In [96]:
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(inputs, labels, stratify=labels, test_size=0.2, random_state=42)

ValueError: The least populated class in y has only 1 member, which is too few. The minimum number of groups for any class cannot be less than 2.

In [93]:
labels[0]

tensor([  0, 158, 628,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0])

In [68]:
[sent_count, max_sent_len]

[211495, 544]

In [15]:
from conllu import parse
import pandas as pd
import os

from common.transliterate import IASTToSlp

def read_split_conllu_file(nfiles, transliterate=False):
    nsentences = []

    for nfile in nfiles:
        # Read the content of your CoNLL-U file
        with open(nfile, "r", encoding="utf-8") as f:
            data = f.read()

        # Parse the CoNLL-U data
        nsentences.append(parse(data))
    
    sentences = [sent for nsent in nsentences for sent in nsent]
    sents = [IASTToSlp(sent.metadata['text']) if transliterate else sent.metadata['text'] for sent in sentences]
    ids = [sent.metadata['sent_id'] for sent in sentences]
    splited = []
    for sentence in sentences:
        all_tokens = []
        for token in sentence:
            if str(token['id']).isdigit():
                token_form = IASTToSlp(token['form']) if transliterate else token['form']
                token_form = token_form.replace("'", 'a', 1)
                all_tokens.append(token_form)
                all_tokens.append("-" if token['feats'] == {'Case': 'Cpd'} else " ")
        splited.append(''.join(all_tokens[:-1]))

    data = {
        'sent_id': ids,
        'src': sents,
        'trg': splited
    }
    return pd.DataFrame(data)

In [69]:
from common.sanskrit_texts import Datasources

pd.set_option('display.max_colwidth', None)

_TEXTS_DIR = '../../../sanskrit_texts'
# Datasources.MAHABHARATA, Datasources.RAMAYANA, Datasources.AMARAKOSHA, 
files = [file for text in [Datasources.HITOPADESHA] for file in get_files_conllu(f"{_TEXTS_DIR}/{text}/")]

df = read_split_conllu_file(files, transliterate=True)
df[:50]

,sent_id,src,trg
0,351391,aTa prAsAdapfzWe suKopavizwAnAM rAjaputrARAM purastAt prastAvakrameRa paRqito 'bravIt,aTa prAsAda-pfzWe suKa-upavizwAnAm rAja-putrARAm purastAt prastAva-krameRa paRqito abravIt
1,351392,Bo rAjaputrAH SfRuta,Bo rAja-putrAH SfRuta
2,351393,kAvyaSAstravinodena kAlo gacCati DImatAm,kAvya-SAstra-vinodena kAlo gacCati DImatAm
3,351394,vyasanena tu mUrKARAM nidrayA kalahena vA,vyasanena tu mUrKARAM nidrayA kalahena vA
4,351395,tad BavatAM vinodAya kAkakUrmAdInAM vicitrAM kaTAM kaTayizyAmi,tad BavatAM vinodAya kAka-kUrma-AdInAm vicitrAM kaTAM kaTayizyAmi
5,351396,rAjaputrEr uktamArya kaTyatAm,rAja-putrEH uktam AryEH kaTyatAm
6,351397,vizRuSarmovAca SfRuta yUyam,vizRuSarmA uvAca SfRuta yUyam
7,351398,samprati mitralABaH prastUyate,samprati mitralABaH prastUyate
8,351399,yasyAyam AdyaH SlokaH,yasya ayam AdyaH SlokaH
9,351400,asADanA vittahInA budDimantaH suhfnmatAH,asADanA vitta-hInAH budDimantaH suhfd-matAH
10,351401,sADayanty ASu kAryARi kAkakUrmamfgAKuvat,sADayanty ASu kAryARi kAka-kUrma-mfga-AKu-vat
11,351402,rAjaputrA UcuH kaTam etat,rAja-putrAH UcuH kaTam etat
12,351403,so 'bravIt,so abravIt
13,351404,asti godAvarItIre viSAlaH SAlmalItaruH,asti godAvarI-tIre viSAlaH SAlmalI-taruH
14,351405,tatra nAnAdigdeSAd Agatya rAtrO pakziRo nivasanti,tatra nAnA diS-deSAt Agatya rAtrO pakziRo nivasanti
15,351406,aTa kadAcid avasannAyAM rAtrO astAcalacUqAvalambini Bagavati kumudinInAyake candramasi,aTa kadAcid avasannAyAM rAtrO astAcala-cUqA-avalambini Bagavati kumudinInAyake candramasi
16,351407,laGupatananAmA vAyasaH prabudDaH kftAntam iva dvitIyam awantaM pASahastaM vyADam apaSyat,vAyasaH prabudDaH kftAntam iva dvitIyam awantaM pASa-hastam vyADam apaSyat
17,351408,tam AlokyAcintayat,tam Alokya acintayat
18,351409,adya prAtar evAnizwadarSanaM jAtam,adya prAtar eva anizwa-darSanam jAtam
19,351410,na jAne kim anaBimataM darSayizyati,na jAne kim anaBimataM darSayizyati
20,351411,ity uktvA tad anusaraRakrameRa vyAkulaS calati,ity uktvA tad anusaraRa-krameRa vyAkulaS calati
21,351412,yataH,yataH
22,351413,SokasTAnasahasrARi BayasTAnaSatAni ca,Soka-sTAna-sahasrARi Baya-sTAna-SatAni ca
23,351414,divase divase mUQam AviSanti na paRqitam,divase divase mUQam AviSanti na paRqitam
24,351415,anyac ca,anyac ca
25,351416,vizayiRAm idam avaSyaM kartavyam,vizayiRAm idam avaSyaM kartavyam
26,351417,utTAyotTAya bodDavyaM kim adya sukftaM kftam,utTAya utTAya bodDavyaM kim adya sukftaM kftam
27,351418,AyuzaH KaRqam AdAya ravir astaM gamizyati,AyuzaH KaRqam AdAya ravir astaM gamizyati
28,351419,aTa tena vyADena taRqulakaRAn vikIrya jAlaM vistIrRam,aTa tena vyADena taRqula-kaRAn vikIrya jAlaM vistIrRam
29,351420,sa ca tatra pracCanno BUtvA sTitaH,sa ca tatra pracCanno BUtvA sTitaH
30,351421,asminn eva kAle citragrIvanAmA kapotarAjaH saparivAro viyati visarpaMs taRqulakaRAn avalokayAmAsa,asminn eva kAle citragrIva-nAmA kapota-rAjaH sa parivAraH viyati visarpaMs taRqula-kaRAn avalokayAmAsa
31,351422,tataH kapotarAjas taRqulakaRalubDAn kapotAn prAha,tataH kapota-rAjaH taRqula-kaRa-lubDAn kapotAn prAha
32,351423,kuto 'tra nirjane vane taRqulakaRAnAM samBavaH,kuto atra nirjane vane taRqula-kaRAnAm samBavaH
33,351424,tan nirUpyatAM tAvat,tan nirUpyatAM tAvat
34,351425,Badram idaM na paSyAmi prAyeRAnena taRqulakaRaloBenAsmABir api taTA Bavitavyam,Badram idaM na paSyAmi prAyeRa anena taRqula-kaRa-loBena asmABiH api taTA Bavitavyam
35,351426,kaNkaRasya tu loBena magnaH paNke sudustare,kaNkaRasya tu loBena magnaH paNke sudustare
36,351427,vfdDavyAGreRa samprAptaH paTikaH saMmftaH,vfdDa vyAGreRa samprAptaH paTikaH saMmftaH
37,351428,kapotA UcuH,kapotA UcuH
38,351429,kaTam etat,kaTam etat
39,351430,so 'bravIt,so abravIt
40,351431,aham ekadA dakziRAraRye carann apaSyam eko vfdDo vyAGraH snAtaH kuSahastaH sarastIre brUte Bo Bo pAnTAH idaM suvarRakaNkaRaM gfhyatAm,aham ekadA dakziRa-araRye carann apaSyam eko vfdDo vyAGraH snAtaH kuSa-hastaH saras-tIre brUte Bo Bo pAnTAH idaM suvarRa-kaNkaRam gfhyatAm
41,351432,tato loBAkfzwena kenacit pAnTena AlocitaM BAgyena etat samBavati,tato loBa-Akfzwena kenacit pAnTena AlocitaM BAgyena etat samBavati
42,351433,kiMtu asmin AtmasaMdehe pravfttir na viDeyA,kim tu asmin Atma-saMdehe pravfttir na viDeyA
43,351434,yataH,yataH
44,351435,anizwAd izwalABe'pi na gatir jAyate SuBA,anizwAd izwa lABe api na gatir jAyate SuBA
45,351436,yatrAste vizasaMsargo 'mftaM tad api mftyave,yatra Aste viza-saMsargaH amftaM tad api mftyave
46,351437,kiMtu sarvatrArTArjanapravfttO saMdeha eva,kim tu sarvatra arTa-arjana-pravfttO saMdeha eva
47,351438,taTA coktam,taTA ca uktam
48,351439,na saMSayam anAruhya naro BadrARi paSyati,na saMSayam an Aruhya naro BadrARi paSyati
49,351440,saMSayaM punar Aruhya yadi jIvati paSyati,saMSayaM punar Aruhya yadi jIvati paSyati

In [70]:
df.shape

(3432, 3)

In [19]:
df[df['sent_id'] == '325497']

,sent_id,src,trg
47270,325497,ke deSAH paridfzwAste kiM ca kAryaM karomi te,ke deSAH paridfzwAH te kiM ca kAryaM karomi te